sudo: false
language: go

go:
- "1.9"
- "1.10"
- "tip"

env:
  global:
    - VERSION=$(cat VERSION)
    - LDFLAGS="-X main.AppVersion=$VERSION"

before_script:
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo ./...

before_deploy:
  - mkdir -p release
  - GOOS=linux  GOARCH=amd64 go build -ldflags "$LDFLAGS" -o release/gucci-v$VERSION-linux-amd64
  - GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o release/gucci-v$VERSION-darwin-amd64

################# RELEASING ####################
## git tag -a vX.X.X -m "release information" ##
## git push --tags origin branch              ##
################################################
deploy:
  provider: releases
  api_key:
    secure: WERQuanRqUFlPZ+qAolZmPjgMAmgQXhdAPPi88xxOukogUtkX4AQieJV5FAxzBUA80OsOUdGp6W8ieraAWC2L1f2nh7i8TQg627CGfeYIG5rncArErGePLXtrOQA5uTpMQzApyNxXdDEtqhZIopjA4BZXljvo1cdpNR355JV9mcYgzJPL+sjz9rgPljCw/1VH0vNRs7lyEzV1+rEm/1XuhEDJuclx8ZHOSguwy17Eao3t+Cpu7Uyih3tMhhE5PRqqgx8sWYwmN1wQEy63MPuvR5LAF2HzPpyVOTRFlxjVVZ5+sXBuiKlIqBWtH0bhyqEsPDUjk8g0LQ9kckbzMbUFzsSM4pFExwuZbrzulpe37om6uTj4+HBGQvcarIm5x8CsJWMWjqSze03r7IAt77Cb7CG+VRx3O7WsAozh7zOL/N8C1l0Xl1DmW2OBILUSjgawTbCOeSFJAkXLlk3RC/awJRgF2759hRC4HNAEFNLI3C5i7dCXBkFgepsuO46uhGef7459iXg+68P4qsEwb+g7b3IXW8ltyVCCTrA5VGwW/vJwNrnn3Blkg8CL0CUYWHVt4PsXwHwTpz9fP9cfkvStkHkddzzl/e5ZFJIcuMuTFkULTWqgM9DxPEi8ysusz3xN6aUNHJGg86VJXgvzRAPvX1WuPQ2qoovq/TTF+iNQh0=
  file:
    - release/gucci-v$VERSION-linux-amd64
    - release/gucci-v$VERSION-darwin-amd64
  skip_cleanup: true
  on:
    repo: noqcks/gucci
    tags: true
